-- Karchy Monochrome for Neovim
--
-- A self-contained colorscheme based on ../colors.toml. The additional blue,
-- cyan, violet, and orange accents give editor syntax a little more range
-- without changing the restrained zinc/indigo character of the desktop theme.

vim.o.background = "dark"
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "karchy-monochrome"

local c = {
  bg = "#18181b",
  bg_dark = "#09090b",
  bg_alt = "#27272a",
  surface = "#27272a",

  fg = "#e4e4e7",
  fg_dark = "#a1a1aa",
  fg_light = "#f4f4f5",
  fg_bright = "#fafafa",
  muted = "#71717a",
  border = "#3f3f46",

  accent = "#a5b4fc",
  accent_strong = "#818cf8",
  selection = "#1e1b4b",

  green = "#34d399",
  red = "#f87171",
  yellow = "#fde68a",

  -- Editor-only accents.
  blue = "#93c5fd",
  cyan = "#67e8f9",
  violet = "#c4b5fd",
  orange = "#fdba74",
}

local groups = {
  -- Editor chrome
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.surface },
  FloatBorder = { fg = c.border, bg = c.surface },
  FloatTitle = { fg = c.accent, bg = c.surface, bold = true },
  ColorColumn = { bg = c.bg_dark },
  Conceal = { fg = c.muted },
  Cursor = { fg = c.bg, bg = c.fg_bright },
  lCursor = { link = "Cursor" },
  CursorIM = { link = "Cursor" },
  CursorColumn = { bg = c.bg_alt },
  CursorLine = { bg = c.bg_alt },
  CursorLineNr = { fg = c.accent, bold = true },
  LineNr = { fg = c.muted },
  LineNrAbove = { fg = c.border },
  LineNrBelow = { fg = c.border },
  SignColumn = { fg = c.muted, bg = c.bg },
  FoldColumn = { fg = c.muted, bg = c.bg },
  Folded = { fg = c.fg_dark, bg = c.bg_alt },
  WinSeparator = { fg = c.border },
  VertSplit = { link = "WinSeparator" },
  StatusLine = { fg = c.fg, bg = c.bg_alt },
  StatusLineNC = { fg = c.muted, bg = c.bg_dark },
  TabLine = { fg = c.muted, bg = c.bg_dark },
  TabLineFill = { bg = c.bg_dark },
  TabLineSel = { fg = c.fg_bright, bg = c.bg_alt, bold = true },
  WinBar = { fg = c.fg, bg = c.bg, bold = true },
  WinBarNC = { fg = c.muted, bg = c.bg },
  Pmenu = { fg = c.fg, bg = c.surface },
  PmenuExtra = { fg = c.muted, bg = c.surface },
  PmenuExtraSel = { fg = c.fg_dark, bg = c.selection },
  PmenuKind = { fg = c.cyan, bg = c.surface },
  PmenuKindSel = { fg = c.cyan, bg = c.selection },
  PmenuMatch = { fg = c.accent, bg = c.surface, bold = true },
  PmenuMatchSel = { fg = c.accent, bg = c.selection, bold = true },
  PmenuSel = { fg = c.fg_bright, bg = c.selection, bold = true },
  PmenuSbar = { bg = c.bg_alt },
  PmenuThumb = { bg = c.muted },
  WildMenu = { fg = c.fg_bright, bg = c.selection, bold = true },
  Visual = { fg = c.fg_bright, bg = c.selection },
  VisualNOS = { link = "Visual" },
  Search = { fg = c.bg, bg = c.yellow },
  IncSearch = { fg = c.bg, bg = c.accent, bold = true },
  CurSearch = { fg = c.bg, bg = c.accent_strong, bold = true },
  Substitute = { fg = c.bg, bg = c.orange, bold = true },
  MatchParen = { fg = c.accent, bold = true, underline = true },
  Directory = { fg = c.blue },
  Title = { fg = c.accent, bold = true },
  Question = { fg = c.green },
  MoreMsg = { fg = c.green },
  ModeMsg = { fg = c.fg, bold = true },
  MsgArea = { fg = c.fg },
  MsgSeparator = { fg = c.border },
  ErrorMsg = { fg = c.red, bold = true },
  WarningMsg = { fg = c.yellow },
  NonText = { fg = c.border },
  Whitespace = { fg = c.border },
  SpecialKey = { fg = c.muted },
  EndOfBuffer = { fg = c.bg },
  QuickFixLine = { fg = c.fg_bright, bg = c.selection },
  qfLineNr = { fg = c.orange },
  qfFileName = { fg = c.blue },
  SpellBad = { sp = c.red, undercurl = true },
  SpellCap = { sp = c.blue, undercurl = true },
  SpellLocal = { sp = c.cyan, undercurl = true },
  SpellRare = { sp = c.violet, undercurl = true },

  -- Vim syntax groups
  Comment = { fg = c.muted, italic = true },
  Constant = { fg = c.yellow },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.orange },
  Boolean = { fg = c.orange, bold = true },
  Float = { link = "Number" },
  Identifier = { fg = c.fg },
  Function = { fg = c.accent },
  Statement = { fg = c.violet },
  Conditional = { fg = c.violet, italic = true },
  Repeat = { fg = c.violet, italic = true },
  Label = { fg = c.blue },
  Operator = { fg = c.fg_dark },
  Keyword = { fg = c.violet, italic = true },
  Exception = { fg = c.red },
  PreProc = { fg = c.blue },
  Include = { fg = c.violet },
  Define = { fg = c.violet },
  Macro = { fg = c.orange },
  PreCondit = { fg = c.violet },
  Type = { fg = c.cyan },
  StorageClass = { fg = c.violet },
  Structure = { fg = c.cyan },
  Typedef = { fg = c.cyan },
  Special = { fg = c.orange },
  SpecialChar = { fg = c.orange },
  Tag = { fg = c.violet },
  Delimiter = { fg = c.fg_dark },
  SpecialComment = { fg = c.muted, bold = true },
  Debug = { fg = c.red },
  Underlined = { fg = c.blue, underline = true },
  Ignore = { fg = c.muted },
  Error = { fg = c.red, bold = true },
  Todo = { fg = c.bg, bg = c.yellow, bold = true },

  -- Diagnostics
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticVirtualTextError = { fg = c.red, bg = c.bg_dark },
  DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.bg_dark },
  DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.bg_dark },
  DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.bg_dark },
  DiagnosticVirtualTextOk = { fg = c.green, bg = c.bg_dark },
  DiagnosticFloatingError = { link = "DiagnosticError" },
  DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
  DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
  DiagnosticFloatingHint = { link = "DiagnosticHint" },
  DiagnosticFloatingOk = { link = "DiagnosticOk" },
  DiagnosticSignError = { link = "DiagnosticError" },
  DiagnosticSignWarn = { link = "DiagnosticWarn" },
  DiagnosticSignInfo = { link = "DiagnosticInfo" },
  DiagnosticSignHint = { link = "DiagnosticHint" },
  DiagnosticSignOk = { link = "DiagnosticOk" },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
  DiagnosticDeprecated = { sp = c.muted, strikethrough = true },
  DiagnosticUnnecessary = { fg = c.muted },

  -- Diffs and version control
  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.red },
  DiffAdd = { fg = c.green, bg = c.bg_dark },
  DiffChange = { fg = c.yellow, bg = c.bg_dark },
  DiffDelete = { fg = c.red, bg = c.bg_dark },
  DiffText = { fg = c.bg, bg = c.yellow, bold = true },
  GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.yellow },
  GitSignsDelete = { fg = c.red },
  GitSignsUntracked = { fg = c.cyan },
  GitSignsCurrentLineBlame = { fg = c.muted, italic = true },
  GitSignsAddPreview = { link = "DiffAdd" },
  GitSignsDeletePreview = { link = "DiffDelete" },
  GitSignsAddInline = { fg = c.green, bg = c.bg_dark },
  GitSignsChangeInline = { fg = c.yellow, bg = c.bg_dark },
  GitSignsDeleteInline = { fg = c.red, bg = c.bg_dark },

  -- LSP references and semantic tokens
  LspReferenceText = { bg = c.bg_alt },
  LspReferenceRead = { bg = c.bg_alt },
  LspReferenceWrite = { bg = c.bg_alt, underline = true },
  LspInlayHint = { fg = c.muted, bg = c.bg_dark, italic = true },
  LspCodeLens = { fg = c.muted },
  LspCodeLensSeparator = { fg = c.border },
  ["@lsp.type.class"] = { link = "Type" },
  ["@lsp.type.decorator"] = { fg = c.orange },
  ["@lsp.type.enum"] = { link = "Type" },
  ["@lsp.type.enumMember"] = { link = "Constant" },
  ["@lsp.type.function"] = { link = "Function" },
  ["@lsp.type.interface"] = { link = "Type" },
  ["@lsp.type.macro"] = { link = "Macro" },
  ["@lsp.type.method"] = { fg = c.blue },
  ["@lsp.type.namespace"] = { fg = c.cyan },
  ["@lsp.type.parameter"] = { fg = c.fg_light },
  ["@lsp.type.property"] = { fg = c.cyan },
  ["@lsp.type.struct"] = { link = "Type" },
  ["@lsp.type.type"] = { link = "Type" },
  ["@lsp.type.typeParameter"] = { fg = c.cyan, italic = true },
  ["@lsp.type.variable"] = { fg = c.fg },
  ["@lsp.mod.deprecated"] = { strikethrough = true },
  ["@lsp.mod.readonly"] = { italic = true },

  -- Tree-sitter captures
  ["@none"] = {},
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.red, italic = true },
  ["@variable.parameter"] = { fg = c.fg_light },
  ["@variable.parameter.builtin"] = { fg = c.orange, italic = true },
  ["@variable.member"] = { fg = c.cyan },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = c.orange, bold = true },
  ["@constant.macro"] = { link = "Macro" },
  ["@module"] = { fg = c.cyan },
  ["@module.builtin"] = { fg = c.cyan, italic = true },
  ["@label"] = { link = "Label" },
  ["@string"] = { link = "String" },
  ["@string.documentation"] = { fg = c.green, italic = true },
  ["@string.regexp"] = { fg = c.orange },
  ["@string.escape"] = { fg = c.cyan },
  ["@string.special"] = { fg = c.orange },
  ["@string.special.symbol"] = { fg = c.violet },
  ["@string.special.path"] = { fg = c.blue, underline = true },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { fg = c.orange },
  ["@boolean"] = { link = "Boolean" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = c.cyan, italic = true },
  ["@type.definition"] = { fg = c.cyan, bold = true },
  ["@attribute"] = { fg = c.orange },
  ["@property"] = { fg = c.cyan },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { fg = c.blue, italic = true },
  ["@function.call"] = { fg = c.accent },
  ["@function.macro"] = { link = "Macro" },
  ["@function.method"] = { fg = c.blue },
  ["@function.method.call"] = { fg = c.blue },
  ["@constructor"] = { fg = c.cyan },
  ["@operator"] = { link = "Operator" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.coroutine"] = { fg = c.violet, italic = true },
  ["@keyword.function"] = { fg = c.violet, italic = true },
  ["@keyword.operator"] = { fg = c.violet },
  ["@keyword.import"] = { fg = c.violet },
  ["@keyword.type"] = { fg = c.violet },
  ["@keyword.modifier"] = { fg = c.violet },
  ["@keyword.repeat"] = { link = "Repeat" },
  ["@keyword.return"] = { fg = c.violet, italic = true },
  ["@keyword.debug"] = { fg = c.red },
  ["@keyword.exception"] = { link = "Exception" },
  ["@keyword.conditional"] = { link = "Conditional" },
  ["@keyword.directive"] = { fg = c.blue },
  ["@keyword.directive.define"] = { link = "Define" },
  ["@punctuation.delimiter"] = { link = "Delimiter" },
  ["@punctuation.bracket"] = { fg = c.fg_dark },
  ["@punctuation.special"] = { fg = c.orange },
  ["@comment"] = { link = "Comment" },
  ["@comment.documentation"] = { fg = c.muted, italic = true },
  ["@comment.error"] = { fg = c.red, bold = true },
  ["@comment.warning"] = { fg = c.yellow, bold = true },
  ["@comment.todo"] = { fg = c.bg, bg = c.yellow, bold = true },
  ["@comment.note"] = { fg = c.bg, bg = c.blue, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = c.accent, bold = true },
  ["@markup.quote"] = { fg = c.fg_dark, italic = true },
  ["@markup.math"] = { fg = c.orange },
  ["@markup.link"] = { fg = c.blue },
  ["@markup.link.label"] = { fg = c.cyan },
  ["@markup.link.url"] = { fg = c.blue, underline = true },
  ["@markup.raw"] = { fg = c.green },
  ["@markup.raw.block"] = { fg = c.green },
  ["@markup.list"] = { fg = c.violet },
  ["@markup.list.checked"] = { fg = c.green },
  ["@markup.list.unchecked"] = { fg = c.muted },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.minus"] = { fg = c.red },
  ["@diff.delta"] = { fg = c.yellow },
  ["@tag"] = { fg = c.violet },
  ["@tag.builtin"] = { fg = c.violet, italic = true },
  ["@tag.attribute"] = { fg = c.orange },
  ["@tag.delimiter"] = { fg = c.fg_dark },

  -- blink.cmp
  BlinkCmpMenu = { link = "Pmenu" },
  BlinkCmpMenuBorder = { link = "FloatBorder" },
  BlinkCmpMenuSelection = { link = "PmenuSel" },
  BlinkCmpLabel = { fg = c.fg },
  BlinkCmpLabelMatch = { fg = c.accent, bold = true },
  BlinkCmpLabelDeprecated = { fg = c.muted, strikethrough = true },
  BlinkCmpLabelDetail = { fg = c.muted },
  BlinkCmpLabelDescription = { fg = c.muted },
  BlinkCmpKind = { fg = c.cyan },
  BlinkCmpSource = { fg = c.muted },
  BlinkCmpDoc = { link = "NormalFloat" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  BlinkCmpDocSeparator = { fg = c.border },
  BlinkCmpDocCursorLine = { link = "CursorLine" },
  BlinkCmpSignatureHelp = { link = "NormalFloat" },
  BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
  BlinkCmpSignatureHelpActiveParameter = { fg = c.accent, bold = true },
  BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
  BlinkCmpScrollBarThumb = { link = "PmenuThumb" },

  -- fzf-lua
  FzfLuaNormal = { link = "NormalFloat" },
  FzfLuaBorder = { link = "FloatBorder" },
  FzfLuaTitle = { link = "FloatTitle" },
  FzfLuaPreviewNormal = { link = "NormalFloat" },
  FzfLuaPreviewBorder = { link = "FloatBorder" },
  FzfLuaPreviewTitle = { link = "FloatTitle" },
  FzfLuaCursorLine = { link = "CursorLine" },
  FzfLuaCursorLineNr = { link = "CursorLineNr" },
  FzfLuaSearch = { link = "IncSearch" },
  FzfLuaHeaderBind = { fg = c.accent },
  FzfLuaHeaderText = { fg = c.fg_dark },
  FzfLuaPathColNr = { fg = c.orange },
  FzfLuaPathLineNr = { fg = c.yellow },
  FzfLuaDirPart = { fg = c.muted },
  FzfLuaFilePart = { fg = c.fg },
  FzfLuaLivePrompt = { fg = c.violet, bold = true },
  FzfLuaLiveSym = { fg = c.cyan },
  FzfLuaFzfMatch = { fg = c.accent, bold = true },
  FzfLuaFzfPointer = { fg = c.violet },
  FzfLuaFzfMarker = { fg = c.green },
  FzfLuaFzfSpinner = { fg = c.cyan },
  FzfLuaFzfPrompt = { fg = c.accent },

  -- mini.files
  MiniFilesNormal = { link = "NormalFloat" },
  MiniFilesBorder = { link = "FloatBorder" },
  MiniFilesBorderModified = { fg = c.yellow, bg = c.surface },
  MiniFilesCursorLine = { link = "CursorLine" },
  MiniFilesDirectory = { link = "Directory" },
  MiniFilesFile = { fg = c.fg },
  MiniFilesTitle = { link = "FloatTitle" },
  MiniFilesTitleFocused = { fg = c.accent, bg = c.surface, bold = true },

}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

local terminal = {
  "#18181b", "#f87171", "#34d399", "#fde68a",
  "#a5b4fc", "#a1a1aa", "#c7d2fe", "#e4e4e7",
  "#71717a", "#fca5a5", "#6ee7b7", "#fef3c7",
  "#c7d2fe", "#d4d4d8", "#e0e7ff", "#fafafa",
}

for index, color in ipairs(terminal) do
  vim.g["terminal_color_" .. (index - 1)] = color
end
